export const cities = [
    'CAIRO', 'ALEXANDRIA', 'PORT SAID', 'SUEZ', 'DAMIETTA',
    'DAKAHLIA', 'SHARQIA', 'QALYUBIA', 'KAFR EL-SHAIKH', 'GHARBIA',
    'MENOFIA', 'BEHEIRA', 'ISMAILIA', 'GIZA', 'BENI SUEF', 'FAIYUM',
    'MINYA', 'ASYUT', 'SOHAG', 'QENA', 'ASWAN', 'LUXOR', 'RED SEA',
    'NEW VALLEY', 'MATRUH', 'NORTH SINAI', 'SOUTH SINAI', 'FOREIGN'
]

